package com.renovite.model;

import java.io.Serializable;

public class IsoField implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// -=---------------------------ISO fields
	// --------------------------------------
	String MSG_TYPE_0;
	String PRIMARY_ACCOUNT_NUMBER_2;
	String PROCESSING_CODE_3;
	long AMOUNT_TRANSACTION_4;
	long AMOUNT_SETTLEMENT_5;
	long AMOUNT_CARDHOLDER_BILLING_6;
	String TRANSMISSION_DATE_AND_TIME_7;
	String AMOUNT_CARDHOLDER_BILLING_FEE_8;
	String CONVERSION_RATE_SETTLEMENT_9;
	String CONVERSION_RATE_CARDHOLDER_BILLING_10;
	String SYSTEM_TRACE_AUDIT_NUMBER_11;
	String TIME_LOCAL_TRANSACTION_12;
	String DATE_LOCAL_TRANSACTION_13;
	String DATE_EXPIRATION_14;
	String DATE_SETTLEMENT_15;
	String DATE_CONVERSION_16;
	String DATE_CAPTURE_17;
	String MERCHANTS_TYPE_18;
	String ACQUIRING_INSTITUTION_COUNTRY_CODE_19;
	String PAN_EXTENDED_COUNTRY_CODE_20;
	String FORWARDING_INSTITUTION_COUNTRY_CODE_21;
	String POINT_OF_SERVICE_ENTRY_MODE_22;
	String CARD_SEQUENCE_NUMBER_23;
	String NETWORK_INTERNATIONAL_IDENTIFIEER_24;
	String POINT_OF_SERVICE_CONDITION_CODE_25;
	String POINT_OF_SERVICE_PIN_CAPTURE_CODE_26;
	String AUTHORIZATION_IDENTIFICATION_RESP_LEN_27;
	String AMOUNT_TRANSACTION_FEE_28;
	String AMOUNT_SETTLEMENT_FEE_29;
	String AMOUNT_TRANSACTION_PROCESSING_FEE_30;
	String AMOUNT_SETTLEMENT_PROCESSING_FEE_31;
	String ACQUIRING_INSTITUTION_IDENT_CODE_32;
	String FORWARDING_INSTITUTION_IDENT_CODE_33;
	String PAN_EXTENDED_34;
	String TRACK_2_DATA_35;
	String TRACK_3_DATA_36;
	String RETRIEVAL_REFERENCE_NUMBER_37;
	String AUTHORIZATION_IDENTIFICATION_RESPONSE_38;
	String RESPONSE_CODE_39;
	String SERVICE_RESTRICTION_CODE_40;
	String CARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41;
	String CARD_ACCEPTOR_IDENTIFICATION_CODE_42;
	String CARD_ACCEPTOR_NAME_OR_LOCATION_43;
	String ADITIONAL_RESPONSE_DATA_44;
	String TRACK_1_DATA_45;
	String ADITIONAL_DATA_ISO_46;
	String ADITIONAL_DATA_NATIONAL_47;
	String ADITIONAL_DATA_PRIVATE_48;
	String CURRENCY_CODE_TRANSACTION_49;
	String CURRENCY_CODE_SETTLEMENT_50;
	String CURRENCY_CODE_CARDHOLDER_BILLING_51;
	String PIN_DATA_52;
	String SECURITY_RELATED_CONTROL_INFORMATION_53;
	String ADDITIONAL_AMOUNTS_54;
	String RESERVED_ISO_55;
	String RESERVED_ISO_56;
	String RESERVED_NATIONAL_57;
	String RESERVED_NATIONAL_58;
	String RESERVED_NATIONAL_59;
	String RESERVED_PRIVATE_60;
	String RESERVED_PRIVATE_61;
	String RESERVED_PRIVATE_62;
	String RESERVED_PRIVATE_63;
	String MESSAGE_AUTHENTICATION_CODE_FIELD_64;
	String BITMAP_EXTENDED_65;
	String SETTLEMENT_CODE_66;
	String EXTENDED_PAYMENT_CODE_67;
	String RECEIVING_INSTITUTION_COUNTRY_CODE_68;
	String SETTLEMENT_INSTITUTION_COUNTRY_CODE_69;
	String NETWORK_MANAGEMENT_INFORMATION_CODE_70;
	String MESSAGE_NUMBER_71;
	String MESSAGE_NUMBER_LAST_72;
	String DATE_ACTION_73;
	String CREDITS_NUMBER_74;
	String CREDITS_REVERSAL_NUMBER_75;
	String DEBITS_NUMBER_76;
	String DEBITS_REVERSAL_NUMBER_77;
	String TRANSFER_NUMBER_78;
	String TRANSFER_REVERSAL_NUMBER_79;
	String INQUIRIES_NUMBER_80;
	String AUTHORIZATION_NUMBER_81;
	String CREDITS_PROCESSING_FEE_AMOUNT_82;
	String CREDITS_TRANSACTION_FEE_AMOUNT_83;
	String DEBITS_PROCESSING_FEE_AMOUNT_84;
	String DEBITS_TRANSACTION_FEE_AMOUNT_85;
	String CREDITS_AMOUNT_86;
	String CREDITS_REVERSAL_AMOUNT_87;
	String DEBITS_AMOUNT_88;
	String DEBITS_REVERSAL_AMOUNT_89;
	String ORIGINAL_DATA_ELEMENTS_90;
	String FILE_UPDATE_CODE_91;
	String FILE_SECURITY_CODE_92;
	String RESPONSE_INDICATOR_93;
	String SERVICE_INDICATOR_94;
	long REPLACEMENT_AMOUNTS_95;
	String MESSAGE_SECURITY_CODE_96;
	String AMOUNT_NET_SETTLEMENT_97;
	String PAYEE_98;
	String SETTLEMENT_INSTITUTION_IDENT_CODE_99;
	String RECEIVING_INSTITUTION_IDENT_CODE_100;
	String FILE_NAME_101;
	String ACCOUNT_IDENTIFICATION_1_102;
	String ACCOUNT_IDENTIFICATION_2_103;
	String TRANSACTION_DESCRIPTION_104;
	String RESERVED_ISO_USE_105;
	String RESERVED_ISO_USE_106;
	String RESERVED_ISO_USE_107;
	String RESERVED_ISO_USE_108;
	String RESERVED_ISO_USE_109;
	String RESERVED_ISO_USE_110;
	String RESERVED_ISO_USE_111;
	String RESERVED_NATIONAL_USE_112;
	String RESERVED_NATIONAL_USE_113;
	String RESERVED_NATIONAL_USE_114;
	String RESERVED_NATIONAL_USE_115;
	String RESERVED_NATIONAL_USE_116;
	String RESERVED_NATIONAL_USE_117;
	String RESERVED_NATIONAL_USE_118;
	String RESERVED_NATIONAL_USE_119;
	String RESERVED_PRIVATE_USE_120;
	String RESERVED_PRIVATE_USE_121;
	String RESERVED_PRIVATE_USE_122;
	String RESERVED_PRIVATE_USE_123;
	String RESERVED_PRIVATE_USE_124;
	String RESERVED_PRIVATE_USE_125;
	String RESERVED_PRIVATE_USE_126;
	String RESERVED_PRIVATE_USE_127;
	String MAC_2_128;

	public String getMSG_TYPE_0() {
		return MSG_TYPE_0;
	}

	public void setMSG_TYPE_0(String mSG_TYPE_0) {
		MSG_TYPE_0 = mSG_TYPE_0;
	}

	public String getPRIMARY_ACCOUNT_NUMBER_2() {
		return PRIMARY_ACCOUNT_NUMBER_2;
	}

	public void setPRIMARY_ACCOUNT_NUMBER_2(String pRIMARY_ACCOUNT_NUMBER_2) {
		PRIMARY_ACCOUNT_NUMBER_2 = pRIMARY_ACCOUNT_NUMBER_2;
	}

	public String getPROCESSING_CODE_3() {
		return PROCESSING_CODE_3;
	}

	public void setPROCESSING_CODE_3(String pROCESSING_CODE_3) {
		PROCESSING_CODE_3 = pROCESSING_CODE_3;
	}

	public long getAMOUNT_TRANSACTION_4() {
		return AMOUNT_TRANSACTION_4;
	}

	public void setAMOUNT_TRANSACTION_4(long aMOUNT_TRANSACTION_4) {
		AMOUNT_TRANSACTION_4 = aMOUNT_TRANSACTION_4;
	}

	public long getAMOUNT_SETTLEMENT_5() {
		return AMOUNT_SETTLEMENT_5;
	}

	public void setAMOUNT_SETTLEMENT_5(long aMOUNT_SETTLEMENT_5) {
		AMOUNT_SETTLEMENT_5 = aMOUNT_SETTLEMENT_5;
	}

	public long getAMOUNT_CARDHOLDER_BILLING_6() {
		return AMOUNT_CARDHOLDER_BILLING_6;
	}

	public void setAMOUNT_CARDHOLDER_BILLING_6(long aMOUNT_CARDHOLDER_BILLING_6) {
		AMOUNT_CARDHOLDER_BILLING_6 = aMOUNT_CARDHOLDER_BILLING_6;
	}

	public String getTRANSMISSION_DATE_AND_TIME_7() {
		return TRANSMISSION_DATE_AND_TIME_7;
	}

	public void setTRANSMISSION_DATE_AND_TIME_7(String tRANSMISSION_DATE_AND_TIME_7) {
		TRANSMISSION_DATE_AND_TIME_7 = tRANSMISSION_DATE_AND_TIME_7;
	}

	public String getAMOUNT_CARDHOLDER_BILLING_FEE_8() {
		return AMOUNT_CARDHOLDER_BILLING_FEE_8;
	}

	public void setAMOUNT_CARDHOLDER_BILLING_FEE_8(String aMOUNT_CARDHOLDER_BILLING_FEE_8) {
		AMOUNT_CARDHOLDER_BILLING_FEE_8 = aMOUNT_CARDHOLDER_BILLING_FEE_8;
	}

	public String getCONVERSION_RATE_SETTLEMENT_9() {
		return CONVERSION_RATE_SETTLEMENT_9;
	}

	public void setCONVERSION_RATE_SETTLEMENT_9(String cONVERSION_RATE_SETTLEMENT_9) {
		CONVERSION_RATE_SETTLEMENT_9 = cONVERSION_RATE_SETTLEMENT_9;
	}

	public String getCONVERSION_RATE_CARDHOLDER_BILLING_10() {
		return CONVERSION_RATE_CARDHOLDER_BILLING_10;
	}

	public void setCONVERSION_RATE_CARDHOLDER_BILLING_10(String cONVERSION_RATE_CARDHOLDER_BILLING_10) {
		CONVERSION_RATE_CARDHOLDER_BILLING_10 = cONVERSION_RATE_CARDHOLDER_BILLING_10;
	}

	public String getSYSTEM_TRACE_AUDIT_NUMBER_11() {
		return SYSTEM_TRACE_AUDIT_NUMBER_11;
	}

	public void setSYSTEM_TRACE_AUDIT_NUMBER_11(String sYSTEM_TRACE_AUDIT_NUMBER_11) {
		SYSTEM_TRACE_AUDIT_NUMBER_11 = sYSTEM_TRACE_AUDIT_NUMBER_11;
	}

	public String getTIME_LOCAL_TRANSACTION_12() {
		return TIME_LOCAL_TRANSACTION_12;
	}

	public void setTIME_LOCAL_TRANSACTION_12(String tIME_LOCAL_TRANSACTION_12) {
		TIME_LOCAL_TRANSACTION_12 = tIME_LOCAL_TRANSACTION_12;
	}

	public String getDATE_LOCAL_TRANSACTION_13() {
		return DATE_LOCAL_TRANSACTION_13;
	}

	public void setDATE_LOCAL_TRANSACTION_13(String dATE_LOCAL_TRANSACTION_13) {
		DATE_LOCAL_TRANSACTION_13 = dATE_LOCAL_TRANSACTION_13;
	}

	public String getDATE_EXPIRATION_14() {
		return DATE_EXPIRATION_14;
	}

	public void setDATE_EXPIRATION_14(String dATE_EXPIRATION_14) {
		DATE_EXPIRATION_14 = dATE_EXPIRATION_14;
	}

	public String getDATE_SETTLEMENT_15() {
		return DATE_SETTLEMENT_15;
	}

	public void setDATE_SETTLEMENT_15(String dATE_SETTLEMENT_15) {
		DATE_SETTLEMENT_15 = dATE_SETTLEMENT_15;
	}

	public String getDATE_CONVERSION_16() {
		return DATE_CONVERSION_16;
	}

	public void setDATE_CONVERSION_16(String dATE_CONVERSION_16) {
		DATE_CONVERSION_16 = dATE_CONVERSION_16;
	}

	public String getDATE_CAPTURE_17() {
		return DATE_CAPTURE_17;
	}

	public void setDATE_CAPTURE_17(String dATE_CAPTURE_17) {
		DATE_CAPTURE_17 = dATE_CAPTURE_17;
	}

	public String getMERCHANTS_TYPE_18() {
		return MERCHANTS_TYPE_18;
	}

	public void setMERCHANTS_TYPE_18(String mERCHANTS_TYPE_18) {
		MERCHANTS_TYPE_18 = mERCHANTS_TYPE_18;
	}

	public String getACQUIRING_INSTITUTION_COUNTRY_CODE_19() {
		return ACQUIRING_INSTITUTION_COUNTRY_CODE_19;
	}

	public void setACQUIRING_INSTITUTION_COUNTRY_CODE_19(String aCQUIRING_INSTITUTION_COUNTRY_CODE_19) {
		ACQUIRING_INSTITUTION_COUNTRY_CODE_19 = aCQUIRING_INSTITUTION_COUNTRY_CODE_19;
	}

	public String getPAN_EXTENDED_COUNTRY_CODE_20() {
		return PAN_EXTENDED_COUNTRY_CODE_20;
	}

	public void setPAN_EXTENDED_COUNTRY_CODE_20(String pAN_EXTENDED_COUNTRY_CODE_20) {
		PAN_EXTENDED_COUNTRY_CODE_20 = pAN_EXTENDED_COUNTRY_CODE_20;
	}

	public String getFORWARDING_INSTITUTION_COUNTRY_CODE_21() {
		return FORWARDING_INSTITUTION_COUNTRY_CODE_21;
	}

	public void setFORWARDING_INSTITUTION_COUNTRY_CODE_21(String fORWARDING_INSTITUTION_COUNTRY_CODE_21) {
		FORWARDING_INSTITUTION_COUNTRY_CODE_21 = fORWARDING_INSTITUTION_COUNTRY_CODE_21;
	}

	public String getPOINT_OF_SERVICE_ENTRY_MODE_22() {
		return POINT_OF_SERVICE_ENTRY_MODE_22;
	}

	public void setPOINT_OF_SERVICE_ENTRY_MODE_22(String pOINT_OF_SERVICE_ENTRY_MODE_22) {
		POINT_OF_SERVICE_ENTRY_MODE_22 = pOINT_OF_SERVICE_ENTRY_MODE_22;
	}

	public String getCARD_SEQUENCE_NUMBER_23() {
		return CARD_SEQUENCE_NUMBER_23;
	}

	public void setCARD_SEQUENCE_NUMBER_23(String cARD_SEQUENCE_NUMBER_23) {
		CARD_SEQUENCE_NUMBER_23 = cARD_SEQUENCE_NUMBER_23;
	}

	public String getNETWORK_INTERNATIONAL_IDENTIFIEER_24() {
		return NETWORK_INTERNATIONAL_IDENTIFIEER_24;
	}

	public void setNETWORK_INTERNATIONAL_IDENTIFIEER_24(String nETWORK_INTERNATIONAL_IDENTIFIEER_24) {
		NETWORK_INTERNATIONAL_IDENTIFIEER_24 = nETWORK_INTERNATIONAL_IDENTIFIEER_24;
	}

	public String getPOINT_OF_SERVICE_CONDITION_CODE_25() {
		return POINT_OF_SERVICE_CONDITION_CODE_25;
	}

	public void setPOINT_OF_SERVICE_CONDITION_CODE_25(String pOINT_OF_SERVICE_CONDITION_CODE_25) {
		POINT_OF_SERVICE_CONDITION_CODE_25 = pOINT_OF_SERVICE_CONDITION_CODE_25;
	}

	public String getPOINT_OF_SERVICE_PIN_CAPTURE_CODE_26() {
		return POINT_OF_SERVICE_PIN_CAPTURE_CODE_26;
	}

	public void setPOINT_OF_SERVICE_PIN_CAPTURE_CODE_26(String pOINT_OF_SERVICE_PIN_CAPTURE_CODE_26) {
		POINT_OF_SERVICE_PIN_CAPTURE_CODE_26 = pOINT_OF_SERVICE_PIN_CAPTURE_CODE_26;
	}

	public String getAUTHORIZATION_IDENTIFICATION_RESP_LEN_27() {
		return AUTHORIZATION_IDENTIFICATION_RESP_LEN_27;
	}

	public void setAUTHORIZATION_IDENTIFICATION_RESP_LEN_27(String aUTHORIZATION_IDENTIFICATION_RESP_LEN_27) {
		AUTHORIZATION_IDENTIFICATION_RESP_LEN_27 = aUTHORIZATION_IDENTIFICATION_RESP_LEN_27;
	}

	public String getAMOUNT_TRANSACTION_FEE_28() {
		return AMOUNT_TRANSACTION_FEE_28;
	}

	public void setAMOUNT_TRANSACTION_FEE_28(String aMOUNT_TRANSACTION_FEE_28) {
		AMOUNT_TRANSACTION_FEE_28 = aMOUNT_TRANSACTION_FEE_28;
	}

	public String getAMOUNT_SETTLEMENT_FEE_29() {
		return AMOUNT_SETTLEMENT_FEE_29;
	}

	public void setAMOUNT_SETTLEMENT_FEE_29(String aMOUNT_SETTLEMENT_FEE_29) {
		AMOUNT_SETTLEMENT_FEE_29 = aMOUNT_SETTLEMENT_FEE_29;
	}

	public String getAMOUNT_TRANSACTION_PROCESSING_FEE_30() {
		return AMOUNT_TRANSACTION_PROCESSING_FEE_30;
	}

	public void setAMOUNT_TRANSACTION_PROCESSING_FEE_30(String aMOUNT_TRANSACTION_PROCESSING_FEE_30) {
		AMOUNT_TRANSACTION_PROCESSING_FEE_30 = aMOUNT_TRANSACTION_PROCESSING_FEE_30;
	}

	public String getAMOUNT_SETTLEMENT_PROCESSING_FEE_31() {
		return AMOUNT_SETTLEMENT_PROCESSING_FEE_31;
	}

	public void setAMOUNT_SETTLEMENT_PROCESSING_FEE_31(String aMOUNT_SETTLEMENT_PROCESSING_FEE_31) {
		AMOUNT_SETTLEMENT_PROCESSING_FEE_31 = aMOUNT_SETTLEMENT_PROCESSING_FEE_31;
	}

	public String getACQUIRING_INSTITUTION_IDENT_CODE_32() {
		return ACQUIRING_INSTITUTION_IDENT_CODE_32;
	}

	public void setACQUIRING_INSTITUTION_IDENT_CODE_32(String aCQUIRING_INSTITUTION_IDENT_CODE_32) {
		ACQUIRING_INSTITUTION_IDENT_CODE_32 = aCQUIRING_INSTITUTION_IDENT_CODE_32;
	}

	public String getFORWARDING_INSTITUTION_IDENT_CODE_33() {
		return FORWARDING_INSTITUTION_IDENT_CODE_33;
	}

	public void setFORWARDING_INSTITUTION_IDENT_CODE_33(String fORWARDING_INSTITUTION_IDENT_CODE_33) {
		FORWARDING_INSTITUTION_IDENT_CODE_33 = fORWARDING_INSTITUTION_IDENT_CODE_33;
	}

	public String getPAN_EXTENDED_34() {
		return PAN_EXTENDED_34;
	}

	public void setPAN_EXTENDED_34(String pAN_EXTENDED_34) {
		PAN_EXTENDED_34 = pAN_EXTENDED_34;
	}

	public String getTRACK_2_DATA_35() {
		return TRACK_2_DATA_35;
	}

	public void setTRACK_2_DATA_35(String tRACK_2_DATA_35) {
		TRACK_2_DATA_35 = tRACK_2_DATA_35;
	}

	public String getTRACK_3_DATA_36() {
		return TRACK_3_DATA_36;
	}

	public void setTRACK_3_DATA_36(String tRACK_3_DATA_36) {
		TRACK_3_DATA_36 = tRACK_3_DATA_36;
	}

	public String getRETRIEVAL_REFERENCE_NUMBER_37() {
		return RETRIEVAL_REFERENCE_NUMBER_37;
	}

	public void setRETRIEVAL_REFERENCE_NUMBER_37(String rETRIEVAL_REFERENCE_NUMBER_37) {
		RETRIEVAL_REFERENCE_NUMBER_37 = rETRIEVAL_REFERENCE_NUMBER_37;
	}

	public String getAUTHORIZATION_IDENTIFICATION_RESPONSE_38() {
		return AUTHORIZATION_IDENTIFICATION_RESPONSE_38;
	}

	public void setAUTHORIZATION_IDENTIFICATION_RESPONSE_38(String aUTHORIZATION_IDENTIFICATION_RESPONSE_38) {
		AUTHORIZATION_IDENTIFICATION_RESPONSE_38 = aUTHORIZATION_IDENTIFICATION_RESPONSE_38;
	}

	public String getRESPONSE_CODE_39() {
		return RESPONSE_CODE_39;
	}

	public void setRESPONSE_CODE_39(String rESPONSE_CODE_39) {
		RESPONSE_CODE_39 = rESPONSE_CODE_39;
	}

	public String getSERVICE_RESTRICTION_CODE_40() {
		return SERVICE_RESTRICTION_CODE_40;
	}

	public void setSERVICE_RESTRICTION_CODE_40(String sERVICE_RESTRICTION_CODE_40) {
		SERVICE_RESTRICTION_CODE_40 = sERVICE_RESTRICTION_CODE_40;
	}

	public String getCARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41() {
		return CARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41;
	}

	public void setCARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41(String cARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41) {
		CARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41 = cARD_ACCEPTOR_TERMINAL_IDENTIFICACION_41;
	}

	public String getCARD_ACCEPTOR_IDENTIFICATION_CODE_42() {
		return CARD_ACCEPTOR_IDENTIFICATION_CODE_42;
	}

	public void setCARD_ACCEPTOR_IDENTIFICATION_CODE_42(String cARD_ACCEPTOR_IDENTIFICATION_CODE_42) {
		CARD_ACCEPTOR_IDENTIFICATION_CODE_42 = cARD_ACCEPTOR_IDENTIFICATION_CODE_42;
	}

	public String getCARD_ACCEPTOR_NAME_OR_LOCATION_43() {
		return CARD_ACCEPTOR_NAME_OR_LOCATION_43;
	}

	public void setCARD_ACCEPTOR_NAME_OR_LOCATION_43(String cARD_ACCEPTOR_NAME_OR_LOCATION_43) {
		CARD_ACCEPTOR_NAME_OR_LOCATION_43 = cARD_ACCEPTOR_NAME_OR_LOCATION_43;
	}

	public String getADITIONAL_RESPONSE_DATA_44() {
		return ADITIONAL_RESPONSE_DATA_44;
	}

	public void setADITIONAL_RESPONSE_DATA_44(String aDITIONAL_RESPONSE_DATA_44) {
		ADITIONAL_RESPONSE_DATA_44 = aDITIONAL_RESPONSE_DATA_44;
	}

	public String getTRACK_1_DATA_45() {
		return TRACK_1_DATA_45;
	}

	public void setTRACK_1_DATA_45(String tRACK_1_DATA_45) {
		TRACK_1_DATA_45 = tRACK_1_DATA_45;
	}

	public String getADITIONAL_DATA_ISO_46() {
		return ADITIONAL_DATA_ISO_46;
	}

	public void setADITIONAL_DATA_ISO_46(String aDITIONAL_DATA_ISO_46) {
		ADITIONAL_DATA_ISO_46 = aDITIONAL_DATA_ISO_46;
	}

	public String getADITIONAL_DATA_NATIONAL_47() {
		return ADITIONAL_DATA_NATIONAL_47;
	}

	public void setADITIONAL_DATA_NATIONAL_47(String aDITIONAL_DATA_NATIONAL_47) {
		ADITIONAL_DATA_NATIONAL_47 = aDITIONAL_DATA_NATIONAL_47;
	}

	public String getADITIONAL_DATA_PRIVATE_48() {
		return ADITIONAL_DATA_PRIVATE_48;
	}

	public void setADITIONAL_DATA_PRIVATE_48(String aDITIONAL_DATA_PRIVATE_48) {
		ADITIONAL_DATA_PRIVATE_48 = aDITIONAL_DATA_PRIVATE_48;
	}

	public String getCURRENCY_CODE_TRANSACTION_49() {
		return CURRENCY_CODE_TRANSACTION_49;
	}

	public void setCURRENCY_CODE_TRANSACTION_49(String cURRENCY_CODE_TRANSACTION_49) {
		CURRENCY_CODE_TRANSACTION_49 = cURRENCY_CODE_TRANSACTION_49;
	}

	public String getCURRENCY_CODE_SETTLEMENT_50() {
		return CURRENCY_CODE_SETTLEMENT_50;
	}

	public void setCURRENCY_CODE_SETTLEMENT_50(String cURRENCY_CODE_SETTLEMENT_50) {
		CURRENCY_CODE_SETTLEMENT_50 = cURRENCY_CODE_SETTLEMENT_50;
	}

	public String getCURRENCY_CODE_CARDHOLDER_BILLING_51() {
		return CURRENCY_CODE_CARDHOLDER_BILLING_51;
	}

	public void setCURRENCY_CODE_CARDHOLDER_BILLING_51(String cURRENCY_CODE_CARDHOLDER_BILLING_51) {
		CURRENCY_CODE_CARDHOLDER_BILLING_51 = cURRENCY_CODE_CARDHOLDER_BILLING_51;
	}

	public String getPIN_DATA_52() {
		return PIN_DATA_52;
	}

	public void setPIN_DATA_52(String pIN_DATA_52) {
		PIN_DATA_52 = pIN_DATA_52;
	}

	public String getSECURITY_RELATED_CONTROL_INFORMATION_53() {
		return SECURITY_RELATED_CONTROL_INFORMATION_53;
	}

	public void setSECURITY_RELATED_CONTROL_INFORMATION_53(String sECURITY_RELATED_CONTROL_INFORMATION_53) {
		SECURITY_RELATED_CONTROL_INFORMATION_53 = sECURITY_RELATED_CONTROL_INFORMATION_53;
	}

	public String getADDITIONAL_AMOUNTS_54() {
		return ADDITIONAL_AMOUNTS_54;
	}

	public void setADDITIONAL_AMOUNTS_54(String aDDITIONAL_AMOUNTS_54) {
		ADDITIONAL_AMOUNTS_54 = aDDITIONAL_AMOUNTS_54;
	}

	public String getRESERVED_ISO_55() {
		return RESERVED_ISO_55;
	}

	public void setRESERVED_ISO_55(String rESERVED_ISO_55) {
		RESERVED_ISO_55 = rESERVED_ISO_55;
	}

	public String getRESERVED_ISO_56() {
		return RESERVED_ISO_56;
	}

	public void setRESERVED_ISO_56(String rESERVED_ISO_56) {
		RESERVED_ISO_56 = rESERVED_ISO_56;
	}

	public String getRESERVED_NATIONAL_57() {
		return RESERVED_NATIONAL_57;
	}

	public void setRESERVED_NATIONAL_57(String rESERVED_NATIONAL_57) {
		RESERVED_NATIONAL_57 = rESERVED_NATIONAL_57;
	}

	public String getRESERVED_NATIONAL_58() {
		return RESERVED_NATIONAL_58;
	}

	public void setRESERVED_NATIONAL_58(String rESERVED_NATIONAL_58) {
		RESERVED_NATIONAL_58 = rESERVED_NATIONAL_58;
	}

	public String getRESERVED_NATIONAL_59() {
		return RESERVED_NATIONAL_59;
	}

	public void setRESERVED_NATIONAL_59(String rESERVED_NATIONAL_59) {
		RESERVED_NATIONAL_59 = rESERVED_NATIONAL_59;
	}

	public String getRESERVED_PRIVATE_60() {
		return RESERVED_PRIVATE_60;
	}

	public void setRESERVED_PRIVATE_60(String rESERVED_PRIVATE_60) {
		RESERVED_PRIVATE_60 = rESERVED_PRIVATE_60;
	}

	public String getRESERVED_PRIVATE_61() {
		return RESERVED_PRIVATE_61;
	}

	public void setRESERVED_PRIVATE_61(String rESERVED_PRIVATE_61) {
		RESERVED_PRIVATE_61 = rESERVED_PRIVATE_61;
	}

	public String getRESERVED_PRIVATE_62() {
		return RESERVED_PRIVATE_62;
	}

	public void setRESERVED_PRIVATE_62(String rESERVED_PRIVATE_62) {
		RESERVED_PRIVATE_62 = rESERVED_PRIVATE_62;
	}

	public String getRESERVED_PRIVATE_63() {
		return RESERVED_PRIVATE_63;
	}

	public void setRESERVED_PRIVATE_63(String rESERVED_PRIVATE_63) {
		RESERVED_PRIVATE_63 = rESERVED_PRIVATE_63;
	}

	public String getMESSAGE_AUTHENTICATION_CODE_FIELD_64() {
		return MESSAGE_AUTHENTICATION_CODE_FIELD_64;
	}

	public void setMESSAGE_AUTHENTICATION_CODE_FIELD_64(String mESSAGE_AUTHENTICATION_CODE_FIELD_64) {
		MESSAGE_AUTHENTICATION_CODE_FIELD_64 = mESSAGE_AUTHENTICATION_CODE_FIELD_64;
	}

	public String getBITMAP_EXTENDED_65() {
		return BITMAP_EXTENDED_65;
	}

	public void setBITMAP_EXTENDED_65(String bITMAP_EXTENDED_65) {
		BITMAP_EXTENDED_65 = bITMAP_EXTENDED_65;
	}

	public String getSETTLEMENT_CODE_66() {
		return SETTLEMENT_CODE_66;
	}

	public void setSETTLEMENT_CODE_66(String sETTLEMENT_CODE_66) {
		SETTLEMENT_CODE_66 = sETTLEMENT_CODE_66;
	}

	public String getEXTENDED_PAYMENT_CODE_67() {
		return EXTENDED_PAYMENT_CODE_67;
	}

	public void setEXTENDED_PAYMENT_CODE_67(String eXTENDED_PAYMENT_CODE_67) {
		EXTENDED_PAYMENT_CODE_67 = eXTENDED_PAYMENT_CODE_67;
	}

	public String getRECEIVING_INSTITUTION_COUNTRY_CODE_68() {
		return RECEIVING_INSTITUTION_COUNTRY_CODE_68;
	}

	public void setRECEIVING_INSTITUTION_COUNTRY_CODE_68(String rECEIVING_INSTITUTION_COUNTRY_CODE_68) {
		RECEIVING_INSTITUTION_COUNTRY_CODE_68 = rECEIVING_INSTITUTION_COUNTRY_CODE_68;
	}

	public String getSETTLEMENT_INSTITUTION_COUNTRY_CODE_69() {
		return SETTLEMENT_INSTITUTION_COUNTRY_CODE_69;
	}

	public void setSETTLEMENT_INSTITUTION_COUNTRY_CODE_69(String sETTLEMENT_INSTITUTION_COUNTRY_CODE_69) {
		SETTLEMENT_INSTITUTION_COUNTRY_CODE_69 = sETTLEMENT_INSTITUTION_COUNTRY_CODE_69;
	}

	public String getNETWORK_MANAGEMENT_INFORMATION_CODE_70() {
		return NETWORK_MANAGEMENT_INFORMATION_CODE_70;
	}

	public void setNETWORK_MANAGEMENT_INFORMATION_CODE_70(String nETWORK_MANAGEMENT_INFORMATION_CODE_70) {
		NETWORK_MANAGEMENT_INFORMATION_CODE_70 = nETWORK_MANAGEMENT_INFORMATION_CODE_70;
	}

	public String getMESSAGE_NUMBER_71() {
		return MESSAGE_NUMBER_71;
	}

	public void setMESSAGE_NUMBER_71(String mESSAGE_NUMBER_71) {
		MESSAGE_NUMBER_71 = mESSAGE_NUMBER_71;
	}

	public String getMESSAGE_NUMBER_LAST_72() {
		return MESSAGE_NUMBER_LAST_72;
	}

	public void setMESSAGE_NUMBER_LAST_72(String mESSAGE_NUMBER_LAST_72) {
		MESSAGE_NUMBER_LAST_72 = mESSAGE_NUMBER_LAST_72;
	}

	public String getDATE_ACTION_73() {
		return DATE_ACTION_73;
	}

	public void setDATE_ACTION_73(String dATE_ACTION_73) {
		DATE_ACTION_73 = dATE_ACTION_73;
	}

	public String getCREDITS_NUMBER_74() {
		return CREDITS_NUMBER_74;
	}

	public void setCREDITS_NUMBER_74(String cREDITS_NUMBER_74) {
		CREDITS_NUMBER_74 = cREDITS_NUMBER_74;
	}

	public String getCREDITS_REVERSAL_NUMBER_75() {
		return CREDITS_REVERSAL_NUMBER_75;
	}

	public void setCREDITS_REVERSAL_NUMBER_75(String cREDITS_REVERSAL_NUMBER_75) {
		CREDITS_REVERSAL_NUMBER_75 = cREDITS_REVERSAL_NUMBER_75;
	}

	public String getDEBITS_NUMBER_76() {
		return DEBITS_NUMBER_76;
	}

	public void setDEBITS_NUMBER_76(String dEBITS_NUMBER_76) {
		DEBITS_NUMBER_76 = dEBITS_NUMBER_76;
	}

	public String getDEBITS_REVERSAL_NUMBER_77() {
		return DEBITS_REVERSAL_NUMBER_77;
	}

	public void setDEBITS_REVERSAL_NUMBER_77(String dEBITS_REVERSAL_NUMBER_77) {
		DEBITS_REVERSAL_NUMBER_77 = dEBITS_REVERSAL_NUMBER_77;
	}

	public String getTRANSFER_NUMBER_78() {
		return TRANSFER_NUMBER_78;
	}

	public void setTRANSFER_NUMBER_78(String tRANSFER_NUMBER_78) {
		TRANSFER_NUMBER_78 = tRANSFER_NUMBER_78;
	}

	public String getTRANSFER_REVERSAL_NUMBER_79() {
		return TRANSFER_REVERSAL_NUMBER_79;
	}

	public void setTRANSFER_REVERSAL_NUMBER_79(String tRANSFER_REVERSAL_NUMBER_79) {
		TRANSFER_REVERSAL_NUMBER_79 = tRANSFER_REVERSAL_NUMBER_79;
	}

	public String getINQUIRIES_NUMBER_80() {
		return INQUIRIES_NUMBER_80;
	}

	public void setINQUIRIES_NUMBER_80(String iNQUIRIES_NUMBER_80) {
		INQUIRIES_NUMBER_80 = iNQUIRIES_NUMBER_80;
	}

	public String getAUTHORIZATION_NUMBER_81() {
		return AUTHORIZATION_NUMBER_81;
	}

	public void setAUTHORIZATION_NUMBER_81(String aUTHORIZATION_NUMBER_81) {
		AUTHORIZATION_NUMBER_81 = aUTHORIZATION_NUMBER_81;
	}

	public String getCREDITS_PROCESSING_FEE_AMOUNT_82() {
		return CREDITS_PROCESSING_FEE_AMOUNT_82;
	}

	public void setCREDITS_PROCESSING_FEE_AMOUNT_82(String cREDITS_PROCESSING_FEE_AMOUNT_82) {
		CREDITS_PROCESSING_FEE_AMOUNT_82 = cREDITS_PROCESSING_FEE_AMOUNT_82;
	}

	public String getCREDITS_TRANSACTION_FEE_AMOUNT_83() {
		return CREDITS_TRANSACTION_FEE_AMOUNT_83;
	}

	public void setCREDITS_TRANSACTION_FEE_AMOUNT_83(String cREDITS_TRANSACTION_FEE_AMOUNT_83) {
		CREDITS_TRANSACTION_FEE_AMOUNT_83 = cREDITS_TRANSACTION_FEE_AMOUNT_83;
	}

	public String getDEBITS_PROCESSING_FEE_AMOUNT_84() {
		return DEBITS_PROCESSING_FEE_AMOUNT_84;
	}

	public void setDEBITS_PROCESSING_FEE_AMOUNT_84(String dEBITS_PROCESSING_FEE_AMOUNT_84) {
		DEBITS_PROCESSING_FEE_AMOUNT_84 = dEBITS_PROCESSING_FEE_AMOUNT_84;
	}

	public String getDEBITS_TRANSACTION_FEE_AMOUNT_85() {
		return DEBITS_TRANSACTION_FEE_AMOUNT_85;
	}

	public void setDEBITS_TRANSACTION_FEE_AMOUNT_85(String dEBITS_TRANSACTION_FEE_AMOUNT_85) {
		DEBITS_TRANSACTION_FEE_AMOUNT_85 = dEBITS_TRANSACTION_FEE_AMOUNT_85;
	}

	public String getCREDITS_AMOUNT_86() {
		return CREDITS_AMOUNT_86;
	}

	public void setCREDITS_AMOUNT_86(String cREDITS_AMOUNT_86) {
		CREDITS_AMOUNT_86 = cREDITS_AMOUNT_86;
	}

	public String getCREDITS_REVERSAL_AMOUNT_87() {
		return CREDITS_REVERSAL_AMOUNT_87;
	}

	public void setCREDITS_REVERSAL_AMOUNT_87(String cREDITS_REVERSAL_AMOUNT_87) {
		CREDITS_REVERSAL_AMOUNT_87 = cREDITS_REVERSAL_AMOUNT_87;
	}

	public String getDEBITS_AMOUNT_88() {
		return DEBITS_AMOUNT_88;
	}

	public void setDEBITS_AMOUNT_88(String dEBITS_AMOUNT_88) {
		DEBITS_AMOUNT_88 = dEBITS_AMOUNT_88;
	}

	public String getDEBITS_REVERSAL_AMOUNT_89() {
		return DEBITS_REVERSAL_AMOUNT_89;
	}

	public void setDEBITS_REVERSAL_AMOUNT_89(String dEBITS_REVERSAL_AMOUNT_89) {
		DEBITS_REVERSAL_AMOUNT_89 = dEBITS_REVERSAL_AMOUNT_89;
	}

	public String getORIGINAL_DATA_ELEMENTS_90() {
		return ORIGINAL_DATA_ELEMENTS_90;
	}

	public void setORIGINAL_DATA_ELEMENTS_90(String oRIGINAL_DATA_ELEMENTS_90) {
		ORIGINAL_DATA_ELEMENTS_90 = oRIGINAL_DATA_ELEMENTS_90;
	}

	public String getFILE_UPDATE_CODE_91() {
		return FILE_UPDATE_CODE_91;
	}

	public void setFILE_UPDATE_CODE_91(String fILE_UPDATE_CODE_91) {
		FILE_UPDATE_CODE_91 = fILE_UPDATE_CODE_91;
	}

	public String getFILE_SECURITY_CODE_92() {
		return FILE_SECURITY_CODE_92;
	}

	public void setFILE_SECURITY_CODE_92(String fILE_SECURITY_CODE_92) {
		FILE_SECURITY_CODE_92 = fILE_SECURITY_CODE_92;
	}

	public String getRESPONSE_INDICATOR_93() {
		return RESPONSE_INDICATOR_93;
	}

	public void setRESPONSE_INDICATOR_93(String rESPONSE_INDICATOR_93) {
		RESPONSE_INDICATOR_93 = rESPONSE_INDICATOR_93;
	}

	public String getSERVICE_INDICATOR_94() {
		return SERVICE_INDICATOR_94;
	}

	public void setSERVICE_INDICATOR_94(String sERVICE_INDICATOR_94) {
		SERVICE_INDICATOR_94 = sERVICE_INDICATOR_94;
	}

	public long getREPLACEMENT_AMOUNTS_95() {
		return REPLACEMENT_AMOUNTS_95;
	}

	public void setREPLACEMENT_AMOUNTS_95(long rEPLACEMENT_AMOUNTS_95) {
		REPLACEMENT_AMOUNTS_95 = rEPLACEMENT_AMOUNTS_95;
	}

	public String getMESSAGE_SECURITY_CODE_96() {
		return MESSAGE_SECURITY_CODE_96;
	}

	public void setMESSAGE_SECURITY_CODE_96(String mESSAGE_SECURITY_CODE_96) {
		MESSAGE_SECURITY_CODE_96 = mESSAGE_SECURITY_CODE_96;
	}

	public String getAMOUNT_NET_SETTLEMENT_97() {
		return AMOUNT_NET_SETTLEMENT_97;
	}

	public void setAMOUNT_NET_SETTLEMENT_97(String aMOUNT_NET_SETTLEMENT_97) {
		AMOUNT_NET_SETTLEMENT_97 = aMOUNT_NET_SETTLEMENT_97;
	}

	public String getPAYEE_98() {
		return PAYEE_98;
	}

	public void setPAYEE_98(String pAYEE_98) {
		PAYEE_98 = pAYEE_98;
	}

	public String getSETTLEMENT_INSTITUTION_IDENT_CODE_99() {
		return SETTLEMENT_INSTITUTION_IDENT_CODE_99;
	}

	public void setSETTLEMENT_INSTITUTION_IDENT_CODE_99(String sETTLEMENT_INSTITUTION_IDENT_CODE_99) {
		SETTLEMENT_INSTITUTION_IDENT_CODE_99 = sETTLEMENT_INSTITUTION_IDENT_CODE_99;
	}

	public String getRECEIVING_INSTITUTION_IDENT_CODE_100() {
		return RECEIVING_INSTITUTION_IDENT_CODE_100;
	}

	public void setRECEIVING_INSTITUTION_IDENT_CODE_100(String rECEIVING_INSTITUTION_IDENT_CODE_100) {
		RECEIVING_INSTITUTION_IDENT_CODE_100 = rECEIVING_INSTITUTION_IDENT_CODE_100;
	}

	public String getFILE_NAME_101() {
		return FILE_NAME_101;
	}

	public void setFILE_NAME_101(String fILE_NAME_101) {
		FILE_NAME_101 = fILE_NAME_101;
	}

	public String getACCOUNT_IDENTIFICATION_1_102() {
		return ACCOUNT_IDENTIFICATION_1_102;
	}

	public void setACCOUNT_IDENTIFICATION_1_102(String aCCOUNT_IDENTIFICATION_1_102) {
		ACCOUNT_IDENTIFICATION_1_102 = aCCOUNT_IDENTIFICATION_1_102;
	}

	public String getACCOUNT_IDENTIFICATION_2_103() {
		return ACCOUNT_IDENTIFICATION_2_103;
	}

	public void setACCOUNT_IDENTIFICATION_2_103(String aCCOUNT_IDENTIFICATION_2_103) {
		ACCOUNT_IDENTIFICATION_2_103 = aCCOUNT_IDENTIFICATION_2_103;
	}

	public String getTRANSACTION_DESCRIPTION_104() {
		return TRANSACTION_DESCRIPTION_104;
	}

	public void setTRANSACTION_DESCRIPTION_104(String tRANSACTION_DESCRIPTION_104) {
		TRANSACTION_DESCRIPTION_104 = tRANSACTION_DESCRIPTION_104;
	}

	public String getRESERVED_ISO_USE_105() {
		return RESERVED_ISO_USE_105;
	}

	public void setRESERVED_ISO_USE_105(String rESERVED_ISO_USE_105) {
		RESERVED_ISO_USE_105 = rESERVED_ISO_USE_105;
	}

	public String getRESERVED_ISO_USE_106() {
		return RESERVED_ISO_USE_106;
	}

	public void setRESERVED_ISO_USE_106(String rESERVED_ISO_USE_106) {
		RESERVED_ISO_USE_106 = rESERVED_ISO_USE_106;
	}

	public String getRESERVED_ISO_USE_107() {
		return RESERVED_ISO_USE_107;
	}

	public void setRESERVED_ISO_USE_107(String rESERVED_ISO_USE_107) {
		RESERVED_ISO_USE_107 = rESERVED_ISO_USE_107;
	}

	public String getRESERVED_ISO_USE_108() {
		return RESERVED_ISO_USE_108;
	}

	public void setRESERVED_ISO_USE_108(String rESERVED_ISO_USE_108) {
		RESERVED_ISO_USE_108 = rESERVED_ISO_USE_108;
	}

	public String getRESERVED_ISO_USE_109() {
		return RESERVED_ISO_USE_109;
	}

	public void setRESERVED_ISO_USE_109(String rESERVED_ISO_USE_109) {
		RESERVED_ISO_USE_109 = rESERVED_ISO_USE_109;
	}

	public String getRESERVED_ISO_USE_110() {
		return RESERVED_ISO_USE_110;
	}

	public void setRESERVED_ISO_USE_110(String rESERVED_ISO_USE_110) {
		RESERVED_ISO_USE_110 = rESERVED_ISO_USE_110;
	}

	public String getRESERVED_ISO_USE_111() {
		return RESERVED_ISO_USE_111;
	}

	public void setRESERVED_ISO_USE_111(String rESERVED_ISO_USE_111) {
		RESERVED_ISO_USE_111 = rESERVED_ISO_USE_111;
	}

	public String getRESERVED_NATIONAL_USE_112() {
		return RESERVED_NATIONAL_USE_112;
	}

	public void setRESERVED_NATIONAL_USE_112(String rESERVED_NATIONAL_USE_112) {
		RESERVED_NATIONAL_USE_112 = rESERVED_NATIONAL_USE_112;
	}

	public String getRESERVED_NATIONAL_USE_113() {
		return RESERVED_NATIONAL_USE_113;
	}

	public void setRESERVED_NATIONAL_USE_113(String rESERVED_NATIONAL_USE_113) {
		RESERVED_NATIONAL_USE_113 = rESERVED_NATIONAL_USE_113;
	}

	public String getRESERVED_NATIONAL_USE_114() {
		return RESERVED_NATIONAL_USE_114;
	}

	public void setRESERVED_NATIONAL_USE_114(String rESERVED_NATIONAL_USE_114) {
		RESERVED_NATIONAL_USE_114 = rESERVED_NATIONAL_USE_114;
	}

	public String getRESERVED_NATIONAL_USE_115() {
		return RESERVED_NATIONAL_USE_115;
	}

	public void setRESERVED_NATIONAL_USE_115(String rESERVED_NATIONAL_USE_115) {
		RESERVED_NATIONAL_USE_115 = rESERVED_NATIONAL_USE_115;
	}

	public String getRESERVED_NATIONAL_USE_116() {
		return RESERVED_NATIONAL_USE_116;
	}

	public void setRESERVED_NATIONAL_USE_116(String rESERVED_NATIONAL_USE_116) {
		RESERVED_NATIONAL_USE_116 = rESERVED_NATIONAL_USE_116;
	}

	public String getRESERVED_NATIONAL_USE_117() {
		return RESERVED_NATIONAL_USE_117;
	}

	public void setRESERVED_NATIONAL_USE_117(String rESERVED_NATIONAL_USE_117) {
		RESERVED_NATIONAL_USE_117 = rESERVED_NATIONAL_USE_117;
	}

	public String getRESERVED_NATIONAL_USE_118() {
		return RESERVED_NATIONAL_USE_118;
	}

	public void setRESERVED_NATIONAL_USE_118(String rESERVED_NATIONAL_USE_118) {
		RESERVED_NATIONAL_USE_118 = rESERVED_NATIONAL_USE_118;
	}

	public String getRESERVED_NATIONAL_USE_119() {
		return RESERVED_NATIONAL_USE_119;
	}

	public void setRESERVED_NATIONAL_USE_119(String rESERVED_NATIONAL_USE_119) {
		RESERVED_NATIONAL_USE_119 = rESERVED_NATIONAL_USE_119;
	}

	public String getRESERVED_PRIVATE_USE_120() {
		return RESERVED_PRIVATE_USE_120;
	}

	public void setRESERVED_PRIVATE_USE_120(String rESERVED_PRIVATE_USE_120) {
		RESERVED_PRIVATE_USE_120 = rESERVED_PRIVATE_USE_120;
	}

	public String getRESERVED_PRIVATE_USE_121() {
		return RESERVED_PRIVATE_USE_121;
	}

	public void setRESERVED_PRIVATE_USE_121(String rESERVED_PRIVATE_USE_121) {
		RESERVED_PRIVATE_USE_121 = rESERVED_PRIVATE_USE_121;
	}

	public String getRESERVED_PRIVATE_USE_122() {
		return RESERVED_PRIVATE_USE_122;
	}

	public void setRESERVED_PRIVATE_USE_122(String rESERVED_PRIVATE_USE_122) {
		RESERVED_PRIVATE_USE_122 = rESERVED_PRIVATE_USE_122;
	}

	public String getRESERVED_PRIVATE_USE_123() {
		return RESERVED_PRIVATE_USE_123;
	}

	public void setRESERVED_PRIVATE_USE_123(String rESERVED_PRIVATE_USE_123) {
		RESERVED_PRIVATE_USE_123 = rESERVED_PRIVATE_USE_123;
	}

	public String getRESERVED_PRIVATE_USE_124() {
		return RESERVED_PRIVATE_USE_124;
	}

	public void setRESERVED_PRIVATE_USE_124(String rESERVED_PRIVATE_USE_124) {
		RESERVED_PRIVATE_USE_124 = rESERVED_PRIVATE_USE_124;
	}

	public String getRESERVED_PRIVATE_USE_125() {
		return RESERVED_PRIVATE_USE_125;
	}

	public void setRESERVED_PRIVATE_USE_125(String rESERVED_PRIVATE_USE_125) {
		RESERVED_PRIVATE_USE_125 = rESERVED_PRIVATE_USE_125;
	}

	public String getRESERVED_PRIVATE_USE_126() {
		return RESERVED_PRIVATE_USE_126;
	}

	public void setRESERVED_PRIVATE_USE_126(String rESERVED_PRIVATE_USE_126) {
		RESERVED_PRIVATE_USE_126 = rESERVED_PRIVATE_USE_126;
	}

	public String getRESERVED_PRIVATE_USE_127() {
		return RESERVED_PRIVATE_USE_127;
	}

	public void setRESERVED_PRIVATE_USE_127(String rESERVED_PRIVATE_USE_127) {
		RESERVED_PRIVATE_USE_127 = rESERVED_PRIVATE_USE_127;
	}

	public String getMAC_2_128() {
		return MAC_2_128;
	}

	public void setMAC_2_128(String mAC_2_128) {
		MAC_2_128 = mAC_2_128;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
