//import com.renovite.model.Cards
import com.renovite.model.IsoField;


rule "MSG_TYPE_0"
salience 4

when
$icsmg:IsoField(MSG_TYPE_0=="0100");
then
 System.out.println("(salience 4)MSG_TYPE_0="+$icsmg.getMSG_TYPE_0());
end

rule "AMOUNT_TRANSACTION_4"
salience 3
when
$icsmg:IsoField(AMOUNT_TRANSACTION_4==441253);
then
 System.out.println("(salience 3)AMOUNT_TRANSACTION_4="+$icsmg.getAMOUNT_TRANSACTION_4());
end



